version: '3'

services:
  sdp-docker:
    image: sdp-docker
    build:
      context: ./SDP-Docker
      dockerfile: Dockerfile
    depends_on:
      - sqldata
  sqldata:
    image: people:10
    build:
      context: ./SQL-Data
      dockerfile: Dockerfile-10
